name: waste_friendly
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"  # Ensure this is properly set for your Flutter version.

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  carousel_slider: ^4.2.1  # Use the latest version available
  cupertino_icons: ^1.0.8  # Icon dependencies.
  table_calendar: ^3.2.0  # This is your calendar dependency.
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^5.0.0  # For linting.

flutter:
  uses-material-design: true  # Ensures Material Design is enabled.
  
  assets:
    - assets/icons/  # Include your icon assets.
    - assets/images/  # Include your image assets.

  # You can uncomment this section to add custom fonts to your application.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic